name: 조건부 배포

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub 에서 레포 받아오기
              uses: actions/checkout@v3

            - name: a 폴더가 변경될 때
#              if: contains(github.event.head_commit.modified, 'a/') || contains(github.event.head_commit.added, 'a/') ||
#                  contains(github.event.head_commit.removed, 'a/')
              run: |
                echo "a 폴더가 변경 됨"
                echo ${{ github.event.head_commit.modified }}
                echo CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
                echo "Changed files: $CHANGED_FILES"

            - name: b 폴더가 변경될 때
              if: contains(github.event.head_commit.modified, 'b/') || contains(github.event.head_commit.added, 'b/') ||
                  contains(github.event.head_commit.removed, 'b/')
              run: |
                echo "b 폴더가 변경될 됨"

            - name: 헤드 커밋 출력
              run: |
                echo '${{ toJson(github.event.head_commit) }}'

            - name: git diff
              run: |
                CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
                echo "Changed files: $CHANGED_FILES"
                echo "files=$CHANGED_FILES" >> $GITHUB_ENV

            - name: github api로 변경된 파일 가져오기
              run: |
                jobs:
    check-pr-changes:
      runs-on: ubuntu-latest
      steps:
        - name: Get PR changed files
          run: |
            CHANGED_FILES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
              | jq -r '.[].filename')
            
            echo "Changed files: $CHANGED_FILES"
            echo "files=$CHANGED_FILES" >> $GITHUB_ENV
